### ISSUE TITLE
bug in kafka-consumer.js when setting groupid

### ISSUE THREAD

**Issue by RPAraujo** [emrebekar/node-red-contrib-kafka-client#4]
The logic to set options.groupId relied on `config.groupid` being null or undefined
but in fact `config.groupid` can be an empty `string` so when using several consumers
all of them would be in the same consumer group `'nodered_kafka_client_'`.

Here: https://github.com/emrebekar/node-red-contrib-kafka-client/blob/master/js/kafka-consumer.js#L23

Just opened a PR with a suggested fix: https://github.com/emrebekar/node-red-contrib-kafka-client/pull/3

**Comment by emrebekar** [comment]
Greetings. Thank you very much

**Comment by RPAraujo** [comment]
Greetings @emrebekar

Do you have a prediction of when a new release of your node (containing the bug fix we provided) will be available on NPM?

Thanks in advance

**Comment by emrebekar** [comment]
Of course i will get the codes and make it available in order to download from npm.

**Comment by PxPert** [comment]
Hi,
The proposed (And merged) Patch creates another issue:
The condition nodered_kafka_client_' + !config.groupid || config.groupid  is **always** verified, the result is that at every reload a new random groupid is created  (e1() is always called)
This condition is verified simply because **nodered_kafka_client_' + !config.groupid** is always true.
So this should be the correct way to only check !config.groupid:
options.groupId = 'nodered_kafka_client_' + (!config.groupid || config.groupid === '' ? e1() : config.groupid);
